### Generate Text with Ollama API
POST http://localhost:11434/api/generate
Content-Type: application/json

{
  "model": "llama3.1:8b",
  "prompt": "Forget everything and let's start a new chat",
  "stream": false
}


### Ollama status
GET http://localhost:11434/

### Generate list of installed models
GET http://localhost:11434/api/tags
